/*******************************************************************************
*
* File Name: appconfig.h
*
* Description: file for static configuration of the application
*              (initial values, interrupt vectors)
*
*****************************************************************************/

#ifndef __APPCONFIG_H
#define __APPCONFIG_H

/*.*************************************************************************
*
*  File generated by Graphical Configuration Tool Tue, 02/Jun/2015, 17:42:23
*
****************************************************************************.*/

#define MC56F84763
#define EXTCLK 8000000L
#define EXTAL 8000000L
#define APPCFG_DFLTS_OMITTED 1
#define APPCFG_GCT_VERSION 0x02061f00L

/*.
    OCCS Configuration
--------------------------------------------
    Use Factory Trim Value: No 
    Temperature trim value for 8 MHz oscillator: 0
    Enable internal 32 kHz oscillator: No 
    Power Down crystal oscillator: No 
    Core frequency: 100 MHz 
    VCO frequency: 400 MHz 
    Loss of lock interrupt 0: Disable 
    Loss of lock interrupt 1: Disable 
    Loss of reference clock Interrupt: Disable
.*/
#define OCCS_CTRL_INIT                    0x0085U
#define OCCS_DIVBY_INIT                   0x2031U
#define OCCS_OSCTL1_INIT                  0x2220U
#define OCCS_USE_FACTORY_TRIM             1
#define OCCS_OSCTL2_INIT                  0x8100U

/*.
    COP Configuration
--------------------------------------------
    COP clock source: Relaxation oscilator 
    COP operation: Enable 
    COP timeout: 8.38848 sec 
    COP Runs in Stop Mode: No 
    COP Runs in Wait Mode: No 
    COP Write Protect: No 
    Enable Loss of Clock COP: No 
    Enable COP Warning Interrupt: No 
    COP Warning Interrupt Timeout: 32.64 ms
.*/
#define COP_COPCTL_INIT                   0x0302U

/*.
    SYS Configuration
--------------------------------------------
    SIM: Power Saving Modes: Stop enabled 
    Wait enabled 
         OnCE clock to processor core: Enabled when core TAP enabled 
    DMA Enable in RUN and WAIT modes: DMA enabled in all power modes 
    Enable External Reset Input Filter : No , SIM - Clock on GPIO: Enable CLKO_0: No 
    SIM - Clock on GPIO: Enable CLKO_1: No 
    SIM - Peripheral Clock Enable: GPIO G: No , GPIO F: Yes, GPIO E: Yes, GPIO D: Yes, GPIO C: Yes, GPIO B: Yes, GPIO A: Yes, TMR A0: No 
                                   TMR A1: No , TMR A2: No , TMR A3: No , TMR B0: Yes, TMR B1: No , TMR B2: No , TMR B3: Yes, DAC: No 
                                   SCI0: Yes, SCI1: Yes, QSPI0: Yes, QSPI1: No , IIC0: No , IIC1: No , FLEXCAN: No 
                                   CMP A: No , CMP B: No , CMP C: No , CMP D: No , SAR ADC: No , CYC ADC: Yes, CRC: No , PIT0: Yes, PIT1: No , PDB0: No , PDB1: No 
                                   PWMCH0: Yes, PWMCH1: Yes, PWMCH2: Yes, PWMCH3: No 
    SIM - Modules Enabled in Stop: GPIO G: No 
                                   GPIO F: No , GPIO E: No , GPIO D: No , GPIO C: No , GPIO B: No , GPIO A: No 
                                   TMR A0: No , TMR A1: No , TMR A2: No , TMR A3: No , TMR B0: No , TMR B1: No , TMR B2: No , TMR B3: No , DAC: No 
                                   SCI0: No , SCI1: No , QSPI0: No , QSPI1: No , IIC0: No , IIC1: No , FLEXCAN: No 
                                   CMP A: No , CMP B: No , CMP C: No , CMP D: No , SAR ADC: No , CYC ADC: No , CRC: No , PIT0: No , PIT1: No , PDB0: No , PDB1: No 
                                   PWMCH0: No , PWMCH1: No , PWMCH2: No , PWMCH3: No 
    Protection of IPS and GPSxx  : Registers not protected 
    Protection of PCE, SD and PCR: Registers not protected 
    Protection of GPIO Port D: Registers not protected 
    Protection of PWRMODE: Registers not protected 
    GPIO Peripheral select registers (GPSn): ANA0/CMPA3 
                                             ANC13 
                                             ANC14 
                                             ANC15 
                                             EXTAL 
                                             TXD0 
                                             RXD0 
                                             XB_IN8 
                                             XB_IN7 
                                             XB_IN3 
                                             SS0_B 
                                             MISO0 
                                             SCLK0 
                                             MOSI0 
                                             CANTX 
                                             CANRX 
                                             XB_IN6 
                                             SDA0 
                                             SCL0 
                                             RXD2 
                                             TXD2 
                                             XB_OUT11 
                                             PWMA_2B 
                                             PWMA_2A 
                                             PWMA_3B 
                                             PWMA_3A 
                                             PWMB_2B 
                                             PWMB_2A 
                                             XB_IN6 
                                             CLKO_1 
                                             SCL1 
                                             SDA1 
                                             TXD1 
                                             RXD1 
                                             TB2 
                                             TB3 
                                             RXD0 
                                             RXD2 
                                             TXD2 
                                             TXD0 
                                             MISO1 
                                             MOSI1 
                                             SCLK1 
                                             RXD0 
                                             PWMB_1B 
                                             PWMB_1A 
                                             PWMB_0B 
                                             PWMB_0A 
                                             PWMB_3B 
                                             PWMB_3A 
                                             PWMA_FAULT4 
                                             PWMA_FAULT5 
                                             PWMB_0X 
                                             PWMB_1X 
                                             PWMB_2X 
                                             TB3 
    Internal Peripheral Select Register 0 (IPS0): GPIO C3 
                                                  GPIO C4 
                                                  GPIO C6/G8 
                                                  GPIO C13/G9 
                                                  XB_OUT34 
                                                  XB_OUT35 
                                                  XB_OUT36 
                                                  XB_OUT37 
                                                  FAULT0 input pin (GPIO E8) 
                                                  FAULT1 input pin (GPIO E9) 
                                                  FAULT2 input pin (GPIO G4) 
                                                  FAULT3 input pin (GPIO G5) 
    Miscellaneous Register 0 (SIM_MISC0): CLKIN0 (GPIOC0 alt1) 
                                          PIT0 master, PIT1 slave 
    SIM - Interrupts: Low voltage 2.2V: Disable
                      Low voltage 2.7V: Disable
                      High voltage 2.2V: Disable
                      High voltage 2.7V: Disable
    Enable Voltage Reference Buffer: No 
    Bandgap trim: 7, Use Factory Trim Value: No 
    Power Control: Large Regulator Standby mode: Normal 
                   Small Regulator 2.7 V Supply Standby mode: Normal 
                   Small Regulator 2.7 V Supply Powerdown mode: Normal 
                   Small Regulator 1.2 V Supply Standby mode: Normal
.*/
#define SIM_CLKOSR_INIT                   0x1020U
#define SIM_GPSCL_INIT                    0x1680U
#define SIM_GPSCH_INIT                    0x0400U
#define SIM_PCE0_INIT                     0x097EU
#define SIM_PCE1_INIT                     0x1A02U
#define SIM_PCE2_INIT                     0x0088U
#define SIM_PCE3_INIT                     0x00E0U
#define SIM_IPS0_INIT                     0xF000U

/*.
    INTC Configuration
--------------------------------------------
.*/
#define INTC_ICTL_INIT                    0x0000U
#define INT_VECTOR_ADDR_21                QT_B3_ISR
#define INT_PRIORITY_LEVEL_21             INTC_LEVEL0
#define INT_VECTOR_ADDR_30                ADC_1_EOS_ISR
#define INT_PRIORITY_LEVEL_30             INTC_LEVEL0
#define INT_VECTOR_ADDR_48                RX1_Full_ISR
#define INT_VECTOR_ADDR_52                RX0_Full_ISR
#define INT_PRIORITY_LEVEL_52             INTC_LEVEL0
#define INT_VECTOR_ADDR_53                TX0_Empty_ISR
#define INT_PRIORITY_LEVEL_53             INTC_LEVEL0
#define INT_VECTOR_ADDR_54                TX0_Empty_ISR
#define INT_PRIORITY_LEVEL_54             INTC_LEVEL0
#define INT_VECTOR_ADDR_60                SPI_0_RX_FULL_ISR
#define INT_VECTOR_ADDR_87                PWM_A0_CompareISR
#define INT_VECTOR_ADDR_95                PIT_0_ISR
#define INT_PRIORITY_LEVEL_95             INTC_LEVEL0

/*.
    QT_B0 Configuration
--------------------------------------------
    Count mode: Gated mode, count primary source rising edges while second input high active 
    Timer Channel Enabled (counter starts counting immediatelly after initialized): Yes
    Primary source: Prescaler (IPB clock/ 1) , Secondary: Counter #0 input pin 
    Input polarity: True , Output polarity: True 
    Input capture mode: Capture disabled, Input Edge Flag disabled 
    Output mode: Asserted while counter is active 
    Count stop mode: Count repeatedly , Count length: Roll over , Count direction: Count up 
    Output enable (OFLAG to pin): No 
    Force OFLAG output at startup: No , Forced OFLAG value: 0
    Master mode (broadcast compare event): Disable
    Enable external OFLAG force (on broadcasted event): No 
    Co-channel initialization (on broadcasted event): No 
    Preload Control: 1: Never , Load Reg: 0
                     2: Never , Load Reg: 0
    Interrupts: Overflow: Disabled
                Input edge: Disabled
                Compare: Disabled
                Cmp 1: Disabled
                Cmp 2: Disabled
    Input Filter: Input Signal Sampling [timer clocks] : 0
                  Consecutive Samples Required to Agree: 3 
                  Input Signal Latency: OFF 
    Fault function: No 
    Alternative Load: No 
    Reload on Capture: No 
    Debug action: Continue 
    Enable DMA write for Comparator Preload Register CMPLD1: No 
    Enable DMA write for Comparator Preload Register CMPLD2: No 
    Enable DMA read for Input Edge Flag: No
.*/
#define QT_B0_CTRL_INIT                   0x7000U

/*.
    QT_B3 Configuration
--------------------------------------------
    Count mode: Stop mode, no operation 
    Timer Channel Enabled (counter starts counting immediatelly after initialized): Yes
    Input polarity: True , Output polarity: True 
    Input capture mode: Capture disabled, Input Edge Flag disabled 
    Output mode: Set on compare, cleared secondary source input edge 
    Count stop mode: Count repeatedly , Count length: Count until compare and reinitialize , Count direction: Count up 
    Output enable (OFLAG to pin): No 
    Force OFLAG output at startup: No , Forced OFLAG value: 0
    Master mode (broadcast compare event): Disable
    Enable external OFLAG force (on broadcasted event): No 
    Co-channel initialization (on broadcasted event): No 
    Preload Control: 1: Never , Load Reg: 0
                     2: Never , Load Reg: 0
    Interrupts: Overflow: Disabled
                Input edge: Disabled
                Compare: Enabled 
                Cmp 1: Disabled
                Cmp 2: Disabled
    Input Filter: Input Signal Sampling [timer clocks] : 0
                  Consecutive Samples Required to Agree: 3 
                  Input Signal Latency: OFF 
    Fault function: No 
    Alternative Load: No 
    Reload on Capture: No 
    Debug action: Continue 
    Enable DMA write for Comparator Preload Register CMPLD1: No 
    Enable DMA write for Comparator Preload Register CMPLD2: No 
    Enable DMA read for Input Edge Flag: No
.*/
#define QT_B3_CTRL_INIT                   0x11A5U
#define QT_B3_SCR_INIT                    0x4000U
#define QT_B3_CMP1_INIT                   0x0BB8U
#define QT_B3_CMP2_INIT                   0x0BB8U

/*.
    PIT_0 Configuration
--------------------------------------------
    Counter Enable: Enable 
    Clock Prescaler: / 8 
    Modulo Value: 12499
    Interrupt Enable: Enable 
    Clock source: IPBus clock
.*/
#define PIT_0_CTRL_INIT                   0x001BU
#define PIT_0_MOD_INIT                    0x30D3U

/*.
    GPIO_A Configuration
--------------------------------------------
    Pin  0: Function: ANA0/CMPA_IN3 , PullUp: Disable , 
    Pin  1: Function: ANA1/CMPA_IN0 , PullUp: Disable , 
    Pin  2: Function: ANA2/VREFHA/CMPA_IN1 , PullUp: Disable , 
    Pin  3: Function: ANA3/VREFLA/CMPA_IN2 , PullUp: Disable , 
    Pin  4: Function: ANA4/ANC8/CMPD_IN0 , PullUp: Disable , 
    Pin  5: Function: GPIO , Direction: Input , PullUp: Disable , Interrupt: Disable, Int.Polarity: Active high , 
    Pin  6: Function: GPIO , Direction: Input , PullUp: Disable , Interrupt: Disable, Int.Polarity: Active high , 
    Pin  7: Function: GPIO , Direction: Input , PullUp: Disable , Interrupt: Disable, Int.Polarity: Active high ,
.*/
#define GPIO_A_PER_INIT                   0x001FU

/*.
    GPIO_B Configuration
--------------------------------------------
    Pin  0: Function: ANB0/CMPB_IN3 , PullUp: Disable , 
    Pin  1: Function: ANB1/CMPB_IN0 , PullUp: Disable , 
    Pin  2: Function: ANB2/VREFHB/CMPC_IN3 , PullUp: Disable , 
    Pin  3: Function: ANB3/VREFLB/CMPC_IN0 , PullUp: Disable , 
    Pin  4: Function: ANB4/ANC12/CMPC_IN1 , PullUp: Disable , 
    Pin  5: Function: GPIO , Direction: Input , PullUp: Disable , Interrupt: Disable, Int.Polarity: Active high , 
    Pin  6: Function: GPIO , Direction: Input , PullUp: Disable , Interrupt: Disable, Int.Polarity: Active high , 
    Pin  7: Function: GPIO , Direction: Input , PullUp: Disable , Interrupt: Disable, Int.Polarity: Active high ,
.*/
#define GPIO_B_PER_INIT                   0x001FU

/*.
    GPIO_C Configuration
--------------------------------------------
    Pin  0: Function: EXTAL , PullUp: Disable , 
    Pin  1: Function: XTAL , PullUp: Disable , 
    Pin  2: Function: TXD0 , PullUp: Disable , 
    Pin  3: Function: GPIO , Direction: Output , Init.Value: Low - 0 , Interrupt: Disable, Int.Polarity: Active high , Output-Mode: Push-pull , 
    Pin  4: Function: XB_IN8 , PullUp: Disable , 
    Pin  5: Function: XB_IN7 , PullUp: Disable , 
    Pin  6: Function: XB_IN3/XB_IN15 , PullUp: Disable , 
    Pin  7: Function: SS0_B , PullUp: Disable , 
    Pin  8: Function: MISO0 , PullUp: Disable , 
    Pin  9: Function: SCLK , PullUp: Disable , 
    Pin 10: Function: MOSI0 , PullUp: Disable , 
    Pin 11: Function: CANTX , PullUp: Disable , 
    Pin 12: Function: CANRX , PullUp: Disable , 
    Pin 13: Function: GPIO , Direction: Output , Init.Value: Low - 0 , Interrupt: Disable, Int.Polarity: Active high , Output-Mode: Push-pull , 
    Pin 14: Function: GPIO , Direction: Input , PullUp: Disable , Interrupt: Disable, Int.Polarity: Active high , 
    Pin 15: Function: GPIO , Direction: Input , PullUp: Disable , Interrupt: Disable, Int.Polarity: Active high ,
.*/
#define GPIO_C_PUR_INIT                   0x2008U
#define GPIO_C_DDR_INIT                   0x2008U
#define GPIO_C_PER_INIT                   0x1FF7U
#define GPIO_C_PUS_INIT                   0xDFFFU

/*.
    GPIO_E Configuration
--------------------------------------------
    Pin  0: Function: PWM0B , PullUp: Disable , 
    Pin  1: Function: PWM0A , PullUp: Disable , 
    Pin  2: Function: PWM1B , PullUp: Disable , 
    Pin  3: Function: PWM1A , PullUp: Disable , 
    Pin  4: Function: PWM2B , PullUp: Disable , 
    Pin  5: Function: PWM2A , PullUp: Disable , 
    Pin  6: Function: GPIO , Direction: Input , PullUp: Disable , Interrupt: Disable, Int.Polarity: Active high , 
    Pin  7: Function: GPIO , Direction: Input , PullUp: Disable , Interrupt: Disable, Int.Polarity: Active high ,
.*/
#define GPIO_E_PER_INIT                   0x003FU
#define GPIO_E_PUS_INIT                   0xFFFCU

/*.
    GPIO_F Configuration
--------------------------------------------
    Pin  0: Function: XB_IN6 , PullUp: Disable , 
    Pin  1: Function: GPIO , Direction: Input , PullUp: Disable , Interrupt: Disable, Int.Polarity: Active high , 
    Pin  2: Function: GPIO , Direction: Input , PullUp: Disable , Interrupt: Disable, Int.Polarity: Active high , 
    Pin  3: Function: GPIO , Direction: Input , PullUp: Disable , Interrupt: Disable, Int.Polarity: Active high , 
    Pin  4: Function: TXD1 , PullUp: Disable , 
    Pin  5: Function: RXD1 , PullUp: Disable , 
    Pin  6: Function: GPIO , Direction: Input , PullUp: Disable , Interrupt: Disable, Int.Polarity: Active high , 
    Pin  7: Function: TB3 , PullUp: Disable , 
    Pin  8: Function: RXD0 , PullUp: Disable ,
.*/
#define GPIO_F_PER_INIT                   0x01B1U

/*.
    XBAR_A Configuration
--------------------------------------------
    0. DMARequest0.: Logic0 
    1. DMARequest1.: Logic0 
    2. DMARequest2.: Logic0 
    3. DMARequest3.: Logic0 
    4. PackagePinGPIO_C14.: Logic0 
    5. PackagePinGPIO_C15.: Logic0 
    6. PackagePinGPIO_F2.: Logic0 
    7. PackagePinGPIO_F3.: Logic0 
    8. PackagePinGPIO_F4.: Logic0 
    9. PackagePinGPIO_F5.: Logic0 
    10. PackagePinGPIO_G8/GPIO_F10.: Logic0 
    11. PackagePinGPIO_G9/GPIO_F9.: Logic0 
    12. ADCA(CyclicADC)Trigger.: PWMA0_TRIG1 
    13. ADCB(CyclicADC)Trigger.: Logic0 
    14. ADCC(SARADC)Trigger.: Logic0 
    15. 12-bitDACSYNC_IN.: Logic0 
    16. ComparatorAWindow/Sample.: Logic0 
    17. ComparatorBWindow/Sample.: Logic0 
    18. ComparatorCWindow/Sample.: Logic0 
    19. ComparatorDWindow/Sample.: Logic0 
    20. PWMA0andPWMB0externalinput.: Logic0 
    21. PWMA1andPWMB2externalinput.: Logic0 
    22. PWMA2andPWMB2externalinput.: Logic0 
    23. PWMA3andPWMB3externalinput.: Logic0 
    24. PWMA0ExternalSynchronizationsignal.: Logic0 
    25. PWMA1ExternalSynchronizationsignal.: Logic0 
    26. PWMA2ExternalSynchronizationsignal.: Logic0 
    27. PWMA3ExternalSynchronizationsignal.: Logic0 
    28. PWMAandPWMBExternalClocksignal.: Logic0 
    29. PWMAandPWMBmoduleFAULT0.: GPIO_C13/GPIO_F0 
    30. PWMAandPWMBmoduleFAULT1.: Logic0 
    31. PWMAandPWMBmoduleFAULT2.: Logic0 
    32. PWMAandPWMBmoduleFAULT3.: Logic0 
    33. PWMAExternalOutputForcesignal.: Logic0 
    34. QuadTimerB0Input.: GPIO_C4/GPIO_B10 
    35. QuadTimerB1Input.: GPIO_C5/GPIO_F1 
    36. QuadTimerB2Input.: GPIO_C6/GPIO_E5/GPIO_F7 
    37. QuadTimerB3Input.: Logic0 
    38. PDB0InputTrigger.: Logic0 
    39. PDB0FaultA.: Logic0 
    40. PDB0FaultC.: Logic0 
    41. PDB1InputTrigger.: Logic0 
    42. PDB1FaultA.: Logic0 
    43. PDB1FaultC.: Logic0 
    44. QuadratureDecoderPhaseA.: Logic0 
    45. QuadratureDecoderPhaseB.: Logic0 
    46. QuadratureDecoderIndex.: Logic0 
    47. QuadratureDecoderHome.: Logic0 
    48. QuadratureDecoderCapture.: Logic0 
    49. QuadTimerA0Input.: GPIO_C4/GPIO_B10 
    50. QuadTimerA1Input.: Logic0 
    51. QuadTimerA2Input.: Logic0 
    52. QuadTimerA3Input.: Logic0 
    53. PWMB0ExternalSynchronizationsignal.: Logic0 
    54. PWMB1ExternalSynchronizationsignal.: Logic0 
    55. PWMB2ExternalSynchronizationsignal.: Logic0 
    56. PWMB3ExternalSynchronizationsignal.: Logic0 
    57. PWMBExternalOutputForcesignal.: Logic0 
    58. ExternalWatchdogMonitor.: Logic0 
    Edge Detection: Never 
    Enable DMA: No 
    Enable Interrupt Out0: No 
    Edge Detection: Never 
    Enable DMA: No 
    Enable Interrupt Out1: No 
    Edge Detection: Never 
    Enable DMA: No 
    Enable Interrupt Out2: No 
    Edge Detection: Never 
    Enable DMA: No 
    Enable Interrupt Out3: No
.*/
#define XBAR_A_SEL6_INIT                  0x0015U
#define XBAR_A_SEL14_INIT                 0x0600U
#define XBAR_A_SEL17_INIT                 0x0708U
#define XBAR_A_SEL18_INIT                 0x0003U
#define XBAR_A_SEL24_INIT                 0x0800U

/*.
    PWM_A_Common Configuration
--------------------------------------------
    Monitor PLL State: Not locked. No PLL check 
    Fault0 Level: Low 
    Fault1 Level: Low 
    Fault2 Level: Low 
    Fault3 Level: Low 
    Fault0 Clearing: Manual 
    Fault1 Clearing: Manual 
    Fault2 Clearing: Manual 
    Fault3 Clearing: Manual 
    Fault0 Safety Mode: Normal 
    Fault1 Safety Mode: Normal 
    Fault2 Safety Mode: Normal 
    Fault3 Safety Mode: Normal 
    Fault Enable Mode: None 
    None: None 
          None 
          None 
    Fault Glitch Stretching: Disabled 
    Fault Filter Period: 0
    Fault Filter Count: 3 
    Fault 0 Pin: Disable
    Fault 1 Pin: Disable
    Fault 2 Pin: Disable
    Fault 3 Pin: Disable
    Submodule 0: Disable Pins PWMA by Fault: Fault 0: No 
                 Disable Pins PWMA by Fault: Fault 1: No 
                 Disable Pins PWMA by Fault: Fault 2: No 
                 Disable Pins PWMA by Fault: Fault 3: No 
                 Disable Pins PWMB by Fault: Fault 0: No 
                 Disable Pins PWMB by Fault: Fault 1: No 
                 Disable Pins PWMB by Fault: Fault 2: No 
                 Disable Pins PWMB by Fault: Fault 3: No 
                 Disable Pins PWMX by Fault: Fault 0: Yes
                 Disable Pins PWMX by Fault: Fault 1: Yes
                 Disable Pins PWMX by Fault: Fault 2: Yes
                 Disable Pins PWMX by Fault: Fault 3: Yes
                 Disable Pins PWMX by Fault: PWMA Fault State: Logic 0 
                 Disable Pins PWMX by Fault: PWMB Fault State: Logic 0 
                 Disable Pins PWMX by Fault: PWMX Fault State: Logic 0 
    Submodule 1: Disable Pins PWMA by Fault: Fault 0: No 
                 Disable Pins PWMA by Fault: Fault 1: No 
                 Disable Pins PWMA by Fault: Fault 2: No 
                 Disable Pins PWMA by Fault: Fault 3: No 
                 Disable Pins PWMB by Fault: Fault 0: No 
                 Disable Pins PWMB by Fault: Fault 1: No 
                 Disable Pins PWMB by Fault: Fault 2: No 
                 Disable Pins PWMB by Fault: Fault 3: No 
                 Disable Pins PWMX by Fault: Fault 0: Yes
                 Disable Pins PWMX by Fault: Fault 1: Yes
                 Disable Pins PWMX by Fault: Fault 2: Yes
                 Disable Pins PWMX by Fault: Fault 3: Yes
                 Disable Pins PWMX by Fault: PWMA Fault State: Logic 0 
                 Disable Pins PWMX by Fault: PWMB Fault State: Logic 0 
                 Disable Pins PWMX by Fault: PWMX Fault State: Logic 0 
    Submodule 2: Disable Pins PWMA by Fault: Fault 0: No 
                 Disable Pins PWMA by Fault: Fault 1: No 
                 Disable Pins PWMA by Fault: Fault 2: No 
                 Disable Pins PWMA by Fault: Fault 3: No 
                 Disable Pins PWMB by Fault: Fault 0: No 
                 Disable Pins PWMB by Fault: Fault 1: No 
                 Disable Pins PWMB by Fault: Fault 2: No 
                 Disable Pins PWMB by Fault: Fault 3: No 
                 Disable Pins PWMX by Fault: Fault 0: Yes
                 Disable Pins PWMX by Fault: Fault 1: Yes
                 Disable Pins PWMX by Fault: Fault 2: Yes
                 Disable Pins PWMX by Fault: Fault 3: Yes
                 Disable Pins PWMX by Fault: PWMA Fault State: Logic 0 
                 Disable Pins PWMX by Fault: PWMB Fault State: Logic 0 
                 Disable Pins PWMX by Fault: PWMX Fault State: Logic 0 
    Submodule 3: Disable Pins PWMA by Fault: Fault 0: Yes
                 Disable Pins PWMA by Fault: Fault 1: Yes
                 Disable Pins PWMA by Fault: Fault 2: Yes
                 Disable Pins PWMA by Fault: Fault 3: Yes
                 Disable Pins PWMB by Fault: Fault 0: Yes
                 Disable Pins PWMB by Fault: Fault 1: Yes
                 Disable Pins PWMB by Fault: Fault 2: Yes
                 Disable Pins PWMB by Fault: Fault 3: Yes
                 Disable Pins PWMX by Fault: Fault 0: Yes
                 Disable Pins PWMX by Fault: Fault 1: Yes
                 Disable Pins PWMX by Fault: Fault 2: Yes
                 Disable Pins PWMX by Fault: Fault 3: Yes
                 Disable Pins PWMX by Fault: PWMA Fault State: Logic 0 
                 Disable Pins PWMX by Fault: PWMB Fault State: Logic 0 
                 Disable Pins PWMX by Fault: PWMX Fault State: Logic 0
.*/
#define PWM_A_MCTRL_INIT                  0x0707U
#define PWM_A_MCTRL2_INIT                 0x0000U

/*.
    PWM_A_FaultCh1 Configuration
--------------------------------------------
    Fault0 Level: Low 
    Fault1 Level: Low 
    Fault2 Level: Low 
    Fault3 Level: Low 
    Fault0 Clearing: Manual 
    Fault1 Clearing: Manual 
    Fault2 Clearing: Manual 
    Fault3 Clearing: Manual 
    Fault0 Safety Mode: Normal 
    Fault1 Safety Mode: Normal 
    Fault2 Safety Mode: Normal 
    Fault3 Safety Mode: Normal 
    Fault Enable Mode: None 
    None: None 
          None 
          None 
    Fault Glitch Stretching: Disabled 
    Fault Filter Period: 0
    Fault Filter Count: 3 
    Fault 4 Pin: Disable
    Fault 5 Pin: Disable
    Fault 6 Pin: Disable
    Fault 7 Pin: Disable
    Submodule 0: Disable Pins PWMA by Fault: Fault 0: No 
                 Disable Pins PWMA by Fault: Fault 1: No 
                 Disable Pins PWMA by Fault: Fault 2: No 
                 Disable Pins PWMA by Fault: Fault 3: No 
                 Disable Pins PWMB by Fault: Fault 0: No 
                 Disable Pins PWMB by Fault: Fault 1: No 
                 Disable Pins PWMB by Fault: Fault 2: No 
                 Disable Pins PWMB by Fault: Fault 3: No 
                 Disable Pins PWMX by Fault: Fault 0: Yes
                 Disable Pins PWMX by Fault: Fault 1: Yes
                 Disable Pins PWMX by Fault: Fault 2: Yes
                 Disable Pins PWMX by Fault: Fault 3: Yes
                 Disable Pins PWMX by Fault: PWMA Fault State: Logic 0 
                 Disable Pins PWMX by Fault: PWMB Fault State: Logic 0 
                 Disable Pins PWMX by Fault: PWMX Fault State: Logic 0 
    Submodule 1: Disable Pins PWMA by Fault: Fault 0: No 
                 Disable Pins PWMA by Fault: Fault 1: No 
                 Disable Pins PWMA by Fault: Fault 2: No 
                 Disable Pins PWMA by Fault: Fault 3: No 
                 Disable Pins PWMB by Fault: Fault 0: No 
                 Disable Pins PWMB by Fault: Fault 1: No 
                 Disable Pins PWMB by Fault: Fault 2: No 
                 Disable Pins PWMB by Fault: Fault 3: No 
                 Disable Pins PWMX by Fault: Fault 0: Yes
                 Disable Pins PWMX by Fault: Fault 1: Yes
                 Disable Pins PWMX by Fault: Fault 2: Yes
                 Disable Pins PWMX by Fault: Fault 3: Yes
                 Disable Pins PWMX by Fault: PWMA Fault State: Logic 0 
                 Disable Pins PWMX by Fault: PWMB Fault State: Logic 0 
                 Disable Pins PWMX by Fault: PWMX Fault State: Logic 0 
    Submodule 2: Disable Pins PWMA by Fault: Fault 0: No 
                 Disable Pins PWMA by Fault: Fault 1: No 
                 Disable Pins PWMA by Fault: Fault 2: No 
                 Disable Pins PWMA by Fault: Fault 3: No 
                 Disable Pins PWMB by Fault: Fault 0: No 
                 Disable Pins PWMB by Fault: Fault 1: No 
                 Disable Pins PWMB by Fault: Fault 2: No 
                 Disable Pins PWMB by Fault: Fault 3: No 
                 Disable Pins PWMX by Fault: Fault 0: Yes
                 Disable Pins PWMX by Fault: Fault 1: Yes
                 Disable Pins PWMX by Fault: Fault 2: Yes
                 Disable Pins PWMX by Fault: Fault 3: Yes
                 Disable Pins PWMX by Fault: PWMA Fault State: Logic 0 
                 Disable Pins PWMX by Fault: PWMB Fault State: Logic 0 
                 Disable Pins PWMX by Fault: PWMX Fault State: Logic 0 
    Submodule 3: Disable Pins PWMA by Fault: Fault 4: Yes
                 Disable Pins PWMA by Fault: Fault 5: Yes
                 Disable Pins PWMA by Fault: Fault 6: Yes
                 Disable Pins PWMA by Fault: Fault 7: Yes
                 Disable Pins PWMB by Fault: Fault 4: Yes
                 Disable Pins PWMB by Fault: Fault 5: Yes
                 Disable Pins PWMB by Fault: Fault 6: Yes
                 Disable Pins PWMB by Fault: Fault 7: Yes
                 Disable Pins PWMX by Fault: Fault 4: Yes
                 Disable Pins PWMX by Fault: Fault 5: Yes
                 Disable Pins PWMX by Fault: Fault 6: Yes
                 Disable Pins PWMX by Fault: Fault 7: Yes
                 Disable Pins PWMX by Fault: PWMA Fault State: Logic 0 
                 Disable Pins PWMX by Fault: PWMB Fault State: Logic 0 
                 Disable Pins PWMX by Fault: PWMX Fault State: Logic 0
.*/

/*.
    PWM_A_0 Configuration
--------------------------------------------
    Debug Mode Operation: Stop 
    Wait Mode Operation: Stop 
    Load Mode: End cycle 
    Load OK: Yes
    PWM Clock Enable: Yes
    Clock Source: IPBus Clock 
    Prescaler: fclk/1 
    INIT register: -3125
    VAL1 register: 3124
    Fraction (FRACVAL1): 0
    Sync. source: Local sync (PWMX) 
    Reload source: This module 
    Reload Frequency: Every opportunity 
    Half Cycle Reload: Disable
    Full Cycle Reload: Enable 
    PWMA Mask: Normal 
    PWMB Mask: Normal 
    PWMX Mask: Normal 
    PWMA Output Polarity: Active High 
    PWMB Output Polarity: Active High 
    PWMX Output Polarity: Active High 
    PWMA Output enable: Disabled 
    PWMB Output enable: Disabled 
    PWMX Output enable: Disabled 
    PWMA and PWMB Pair Operation: Complementary 
    Initialize value registers: Enable 
    PWM Value 2: -1562
    PWM Value 3: 1562
    PWM Value 4: -1562
    PWM Value 5: 3123
    PWM Value X: 0
    Value 0: Disable
    Value1: Disable
    Value 2: Disable
    Value3: Disable
    Value 4: Disable
    Value5: Enable 
    Double Switching: PWM23 
    Deadtime count 1: 100
    Software Controlled Output: Logic 0 
                                Logic 0 
    Force Initialization Enable: No 
    Source of FORCE OUTPUT signal: Local force CTRL2[FORCE] 
    Dead Time Source 23: PWM23 
    Dead Time Source 45: PWM45 
    PWM45 Initial Value: Logic 0 
                         Logic 0 
    PWMX Initial Value: Logic 0 
    Reload: Disable
    Reload Error: Disable
    Value 0 Compare: Disable
    Value 1 Compare: Disable
    Value 2 Compare: Disable
    Value 3 Compare: Disable
    Value 4 Compare: Disable
    Value 5 Compare: Disable
    Capture A0: Disable
    Capture A1: Disable
    Capture B0: Disable
    Capture B1: Disable
    Capture X0: Disable
    Capture X1: Disable
    Capture A Input select: Raw PWMA input 
    Capture B Input select: Raw PWMA input 
    Capture X Input select: Raw PWMA input 
    One Shot mode enable: Disable
                          Disable
                          Disable
    Edge Counter Enable: Enable 
                         Enable 
                         Enable 
    Edge Compare A Value: 0
    Edge Compare B Value: 0
    Edge Compare X Value: 0
    Capture A0 Edge Select: Rising 
    Capture A1 Edge Select: Falling 
    Capture B0 Edge Select: Rising 
    Capture B1 Edge Select: Falling 
    Capture X0 Edge Select: Rising 
    Capture X1 Edge Select: Falling 
    PWMX Double Switching: Disable
    Capture A0: Disable
    Capture A1: Disable
    Capture B0: Disable
    Capture B1: Disable
    Capture X0: Disable
    Capture X1: Disable
    Source of capture DMA: DMA disabled 
    Enable DMA Write Requests For alue Registers: No 
    Output Trigger 0 Source: PWM_OUT_TRIG0 
    Output Trigger 1 Source: PWM_OUT_TRIG1
.*/
#define PWM_A_0_CTRL_INIT                 0x0400U
#define PWM_A_0_CTRL2_INIT                0x0000U
#define PWM_A_0_USE_PWMVAL                1
#define PWM_A_0_INIT_INIT                 0xF3CBU
#define PWM_A_0_VAL1_INIT                 0x0C34U
#define PWM_A_0_VAL0_INIT                 0x0000U
#define PWM_A_0_VAL2_INIT                 0xF9E6U
#define PWM_A_0_VAL3_INIT                 0x061AU
#define PWM_A_0_VAL4_INIT                 0xF9E6U
#define PWM_A_0_VAL5_INIT                 0x0C33U
#define PWM_A_0_FRACVAL2_INIT             0x0000U
#define PWM_A_0_FRACVAL3_INIT             0x0000U
#define PWM_A_0_FRACVAL4_INIT             0x0000U
#define PWM_A_0_FRACVAL5_INIT             0x0000U
#define PWM_A_0_TCTRL_INIT                0x0020U
#define PWM_A_0_DTCNT0_INIT               0x0064U
#define PWM_A_0_DTCNT1_INIT               0x0064U
#define PWM_A_0_DISMAP0_INIT              0xFF00U
#define PWM_A_0_CAPTCTRLA_INIT            0x0098U
#define PWM_A_0_CAPTCTRLB_INIT            0x0098U
#define PWM_A_0_CAPTCTRLX_INIT            0x0098U
#define PWM_A_0_DISMAP1_INIT              0xFF00U

/*.
    PWM_A_1 Configuration
--------------------------------------------
    Debug Mode Operation: Stop 
    Wait Mode Operation: Stop 
    Load Mode: End cycle 
    Load OK: Yes
    PWM Clock Enable: Yes
    Clock Source: PWM_0 clock 
    Prescaler: fclk/1 
    INIT register: -3125
    VAL1 register: 0
    Fraction (FRACVAL1): 0
    Sync. source: Master sync (PWM_0) 
    Reload source: PWM_0 module 
    Reload Frequency: Every opportunity 
    Half Cycle Reload: Disable
    Full Cycle Reload: Enable 
    PWMA Mask: Normal 
    PWMB Mask: Normal 
    PWMX Mask: Normal 
    PWMA Output Polarity: Active High 
    PWMB Output Polarity: Active High 
    PWMX Output Polarity: Active High 
    PWMA Output enable: Disabled 
    PWMB Output enable: Disabled 
    PWMX Output enable: Disabled 
    PWMA and PWMB Pair Operation: Complementary 
    Initialize value registers: Enable 
    PWM Value 2: -1562
    PWM Value 3: 1562
    PWM Value 4: -1562
    PWM Value 5: 1562
    PWM Value X: 0
    Value 0: Disable
    Value1: Disable
    Value 2: Disable
    Value3: Disable
    Value 4: Disable
    Value5: Disable
    Double Switching: PWM23 
    Deadtime count 1: 100
    Software Controlled Output: Logic 0 
                                Logic 0 
    Force Initialization Enable: No 
    Source of FORCE OUTPUT signal: Local force CTRL2[FORCE] 
    Dead Time Source 23: PWM23 
    Dead Time Source 45: PWM45 
    PWM45 Initial Value: Logic 0 
                         Logic 0 
    PWMX Initial Value: Logic 0 
    Reload: Disable
    Reload Error: Disable
    Value 0 Compare: Disable
    Value 1 Compare: Disable
    Value 2 Compare: Disable
    Value 3 Compare: Disable
    Value 4 Compare: Disable
    Value 5 Compare: Disable
    Capture A0: Disable
    Capture A1: Disable
    Capture B0: Disable
    Capture B1: Disable
    Capture X0: Disable
    Capture X1: Disable
    Capture A Input select: Raw PWMA input 
    Capture B Input select: Raw PWMA input 
    Capture X Input select: Raw PWMA input 
    One Shot mode enable: Disable
                          Disable
                          Disable
    Edge Counter Enable: Disable
                         Disable
                         Disable
    Edge Compare A Value: 0
    Edge Compare B Value: 0
    Edge Compare X Value: 0
    Capture A0 Edge Select: Disabled 
    Capture A1 Edge Select: Disabled 
    Capture B0 Edge Select: Disabled 
    Capture B1 Edge Select: Disabled 
    Capture X0 Edge Select: Rising 
    Capture X1 Edge Select: Falling 
    PWMX Double Switching: Disable
    Capture A0: Disable
    Capture A1: Disable
    Capture B0: Disable
    Capture B1: Disable
    Capture X0: Disable
    Capture X1: Disable
    Source of capture DMA: DMA disabled 
    Enable DMA Write Requests For alue Registers: No 
    Output Trigger 0 Source: PWM_OUT_TRIG0 
    Output Trigger 1 Source: PWM_OUT_TRIG1
.*/
#define PWM_A_1_CTRL_INIT                 0x0400U
#define PWM_A_1_CTRL2_INIT                0x0206U
#define PWM_A_1_USE_PWMVAL                1
#define PWM_A_1_INIT_INIT                 0xF3CBU
#define PWM_A_1_VAL1_INIT                 0x0000U
#define PWM_A_1_VAL0_INIT                 0x0000U
#define PWM_A_1_VAL2_INIT                 0xF9E6U
#define PWM_A_1_VAL3_INIT                 0x061AU
#define PWM_A_1_VAL4_INIT                 0xF9E6U
#define PWM_A_1_VAL5_INIT                 0x061AU
#define PWM_A_1_FRACVAL2_INIT             0x0000U
#define PWM_A_1_FRACVAL3_INIT             0x0000U
#define PWM_A_1_FRACVAL4_INIT             0x0000U
#define PWM_A_1_FRACVAL5_INIT             0x0000U
#define PWM_A_1_DTCNT0_INIT               0x0064U
#define PWM_A_1_DTCNT1_INIT               0x0064U
#define PWM_A_1_DISMAP0_INIT              0xFF00U
#define PWM_A_1_CAPTCTRLX_INIT            0x0018U
#define PWM_A_1_DISMAP1_INIT              0xFF00U

/*.
    PWM_A_2 Configuration
--------------------------------------------
    Debug Mode Operation: Stop 
    Wait Mode Operation: Stop 
    Load Mode: End cycle 
    Load OK: Yes
    PWM Clock Enable: Yes
    Clock Source: PWM_0 clock 
    Prescaler: fclk/1 
    INIT register: -3125
    VAL1 register: 0
    Fraction (FRACVAL1): 0
    Sync. source: Master sync (PWM_0) 
    Reload source: PWM_0 module 
    Reload Frequency: Every opportunity 
    Half Cycle Reload: Disable
    Full Cycle Reload: Enable 
    PWMA Mask: Normal 
    PWMB Mask: Normal 
    PWMX Mask: Normal 
    PWMA Output Polarity: Active High 
    PWMB Output Polarity: Active High 
    PWMX Output Polarity: Active High 
    PWMA Output enable: Disabled 
    PWMB Output enable: Disabled 
    PWMX Output enable: Disabled 
    PWMA and PWMB Pair Operation: Complementary 
    Initialize value registers: Enable 
    PWM Value 2: -1562
    PWM Value 3: 1562
    PWM Value 4: -1562
    PWM Value 5: 1562
    PWM Value X: 0
    Value 0: Disable
    Value1: Disable
    Value 2: Disable
    Value3: Disable
    Value 4: Disable
    Value5: Disable
    Double Switching: PWM23 
    Deadtime count 1: 100
    Software Controlled Output: Logic 0 
                                Logic 0 
    Force Initialization Enable: No 
    Source of FORCE OUTPUT signal: Local force CTRL2[FORCE] 
    Dead Time Source 23: PWM23 
    Dead Time Source 45: PWM45 
    PWM45 Initial Value: Logic 0 
                         Logic 0 
    PWMX Initial Value: Logic 0 
    Reload: Disable
    Reload Error: Disable
    Value 0 Compare: Disable
    Value 1 Compare: Disable
    Value 2 Compare: Disable
    Value 3 Compare: Disable
    Value 4 Compare: Disable
    Value 5 Compare: Disable
    Capture A0: Disable
    Capture A1: Disable
    Capture B0: Disable
    Capture B1: Disable
    Capture X0: Disable
    Capture X1: Disable
    Capture A Input select: Raw PWMA input 
    Capture B Input select: Raw PWMA input 
    Capture X Input select: Raw PWMA input 
    One Shot mode enable: Disable
                          Disable
                          Disable
    Edge Counter Enable: Disable
                         Disable
                         Disable
    Edge Compare A Value: 0
    Edge Compare B Value: 0
    Edge Compare X Value: 0
    Capture A0 Edge Select: Disabled 
    Capture A1 Edge Select: Disabled 
    Capture B0 Edge Select: Disabled 
    Capture B1 Edge Select: Disabled 
    Capture X0 Edge Select: Rising 
    Capture X1 Edge Select: Falling 
    PWMX Double Switching: Disable
    Capture A0: Disable
    Capture A1: Disable
    Capture B0: Disable
    Capture B1: Disable
    Capture X0: Disable
    Capture X1: Disable
    Source of capture DMA: DMA disabled 
    Enable DMA Write Requests For alue Registers: No 
    Output Trigger 0 Source: PWM_OUT_TRIG0 
    Output Trigger 1 Source: PWM_OUT_TRIG1
.*/
#define PWM_A_2_CTRL_INIT                 0x0400U
#define PWM_A_2_CTRL2_INIT                0x0206U
#define PWM_A_2_USE_PWMVAL                1
#define PWM_A_2_INIT_INIT                 0xF3CBU
#define PWM_A_2_VAL1_INIT                 0x0000U
#define PWM_A_2_VAL0_INIT                 0x0000U
#define PWM_A_2_VAL2_INIT                 0xF9E6U
#define PWM_A_2_VAL3_INIT                 0x061AU
#define PWM_A_2_VAL4_INIT                 0xF9E6U
#define PWM_A_2_VAL5_INIT                 0x061AU
#define PWM_A_2_FRACVAL2_INIT             0x0000U
#define PWM_A_2_FRACVAL3_INIT             0x0000U
#define PWM_A_2_FRACVAL4_INIT             0x0000U
#define PWM_A_2_FRACVAL5_INIT             0x0000U
#define PWM_A_2_DTCNT0_INIT               0x0064U
#define PWM_A_2_DTCNT1_INIT               0x0064U
#define PWM_A_2_DISMAP0_INIT              0xFF00U
#define PWM_A_2_CAPTCTRLX_INIT            0x0018U
#define PWM_A_2_DISMAP1_INIT              0xFF00U

/*.
    PWM_A_SW_LAYER Configuration
--------------------------------------------
.*/
#define PWM_A_SW_LAYER_THREE_PHASE_CONF   0x0100U

/*.
    ADC_1 Configuration
--------------------------------------------
    Clock frequency: 10 MHz 
    Trigger source: SYNC0 input 
    Channel Configuration: ANA0-ANA1: Single ended , ANA2-ANA3: Single ended 
                           ANB0-ANB1: Single ended , ANB2-ANB3: Single ended 
                           ANA4-ANA5: Single ended , ANA6-ANA7: Single ended 
                           ANB4-ANB5: Single ended , ANB6-ANB7: Single ended 
    Channel to Sample Mapping: SMP0: ANA0 , SMP1: ANA1 , SMP2: ANA2 , SMP3: ANA3 
                               SMP4: ANA4 , 
                               SMP8: ANB0 , SMP9: ANB1 , SMP10 : ANB2 , SMP11: ANB3 
                               SMP12: ANB4 , 
    Scan Mode: Triggered parallel 
    ANB simulataneous to ANA: Yes
    Enabled samples: / SMP0 SMP1 SMP2 SMP3 / SMP4 / SMP8 SMP9 SMP10 SMP11 / SMP12 
    Zero crossing mode: SMP0: Disabled , SMP1: Disabled , SMP2: Disabled , SMP3: Disabled 
                        SMP4: Disabled , SMP5: Disabled , SMP6: Disabled , SMP7: Disabled 
                        SMP8: Disabled , SMP9: Disabled , SMP10: Disabled , SMP11: Disabled 
                        Disabled: Disabled , SMP12: Disabled , SMP13: Disabled , SMP14: Disabled 
    Auto Power Down Mode: Disable
    Auto Stand-by Mode: Disable
    Power down converter A (ANA0-ANA7): No 
    Power down converter B (ANB0-ANB7): No 
    Power down voltage reference: Yes
    Power up delay: 26, Power Control: 2.6 us 
    Converter1 VREFLO source: Internal VSSA
    Converter1 VREFH  source: Internal VDDA
    Converter0 VREFLO source: Internal VSSA
    Converter0 VREFH  source: Internal VDDA
    Interrupts: ANA Conversion complete: Enabled 
                High limit error: Disabled
                Low limit error: Disabled
                Zero crossing: Disabled
    ANA channel Gain Configuration: Gain ANA0: 1x , Gain ANA1: 1x 
                                    Gain ANA2: 1x , Gain ANA3: 1x 
                                    Gain ANA4: 1x , Gain ANA5: 1x 
                                    Gain ANA6: 1x , Gain ANA7: 1x 
    ANB channel Gain Configuration: Gain ANB0: 1x , Gain ANB1: 1x 
                                    Gain ANB2: 1x , Gain ANB3: 1x 
                                    Gain ANB4: 1x , Gain ANB5: 1x 
                                    Gain ANB6: 1x , Gain ANB7: 1x 
    Power Mode: Power mode ANA: up to 10MHz 
                Power mode ANB: up to 10MHz 
    ANA Enable: No 
    ANB Enable: No 
    DMA Trigger Source: End Scan 
    Sample Window Count0: Start-up Mode: 2
.*/
#define ADC_1_ADCR1_INIT                  0x1805U
#define ADC_1_ADCR2_INIT                  0x5049U
#define ADC_1_ADLST1_INIT                 0x3210U
#define ADC_1_ADLST2_INIT                 0x7654U
#define ADC_1_ADLST3_INIT                 0xBA98U
#define ADC_1_ADLST4_INIT                 0xFEDCU
#define ADC_1_ADSDIS_INIT                 0xE0E0U
#define ADC_1_ADOFS0_INIT                 0x4000U
#define ADC_1_ADCPOWER_INIT               0x1DA4U
#define ADC_1_ADCPWR2_INIT                0x0405U
#define ADC_1_ADOFS8_INIT                 0x4000U

/*.
    SCI_0 Configuration
--------------------------------------------
    Baudrate: 57604 bps 
    Enable Receiver: Enable 
    Enable Transmitter: Enable 
    Data word length: 8 bits 
    Parity: None 
    Polarity: True polarity 
    Loop mode: Disable
    Function in Wait Mode: SCI module enabled in Wait Mode 
    Interrupts: RX Full: Enable 
                RX Error: Disable
                TX Empty: Disable
                TX Empty: Disable
    Enable RX and TX FIFO Queues: Disable
    RX Active Edge: Disable
    Enable TX DMA: Disable
    Enable RX DMA: Disable
    Hold off entry to stop mode: No 
    Rx Idle: Disable
.*/
#define SCI_0_SCIBR_INIT                  0x0364U
#define SCI_0_SCICR_INIT                  0x002CU
#define SCI_0_SCICR2_INIT                 0x0000U
#define SCI_0_RX_BUFFER_OKLIMIT           0x000FU
#define SCI_0_RX_BUFFER_LOWLIMIT          0x000AU
#define SCI_0_SCICR3_INIT                 0x0000U

/*.
    SCI_1 Configuration
--------------------------------------------
    Baudrate: 19201 bps 
    Enable Receiver: Enable 
    Enable Transmitter: Enable 
    Data word length: 8 bits 
    Parity: None 
    Polarity: True polarity 
    Loop mode: Disable
    Function in Wait Mode: SCI module enabled in Wait Mode 
    Interrupts: RX Full: Disable
                RX Error: Disable
                TX Empty: Disable
                TX Empty: Disable
    Enable RX and TX FIFO Queues: Disable
    RX Active Edge: Disable
    Enable TX DMA: Disable
    Enable RX DMA: Disable
    Hold off entry to stop mode: No 
    Rx Idle: Disable
.*/
#define SCI_1_SCIBR_INIT                  0x0A2CU
#define SCI_1_SCICR_INIT                  0x000CU
#define SCI_1_SCICR2_INIT                 0x0000U
#define SCI_1_RX_BUFFER_OKLIMIT           0x000FU
#define SCI_1_RX_BUFFER_LOWLIMIT          0x000AU
#define SCI_1_SCICR3_INIT                 0x0000U

/*.
    SPI_0 Configuration
--------------------------------------------
    SPI Module Enable: Enable 
    Clock frequency: 1.5625 MHz 
    SPI Mode: Master 
    SCLK Polarity: Falling edge 
    SCLK Phase: Transmission started by 1st SCLK edge 
    Shift order: MSB first 
    Wired OR mode: Normal 
    SS Mode Fault Enable: Disable
    Interrupts: Receiver: Enable 
                Error: Disable
                Transmitter: Disable
    Enable RX and TX FIFO Queues: Disable
    TX DMA Enable: Disable
    RX DMA Enable: Disable
    Stop Mode Holdoff Enable: Disable
.*/
#define SPI_0_SPDSCR_INIT                 0x058FU
#define SPI_0_SPSCR_INIT                  0xA360U

/*.
    FMSTR Configuration
--------------------------------------------
.*/
#define FMSTR_COMM_INTERFACE              2
#define FMSTR_LONG_INTR                   0
#define FMSTR_SHORT_INTR                  0
#define FMSTR_POLL_DRIVEN                 1
#define FMSTR_USE_SCOPE                   1
#define FMSTR_USE_RECORDER                1
#define FMSTR_REC_BUFF_SIZE               8192


/*.         End of autogenerated code
********************************************************************** ..*/

#endif
